### ISSUE TITLE
Failed to find asm code

### ISSUE THREAD

**Issue by paulwrubel** [HaloMods/HaloWarsDocs#2]
Met with this error upon using exe on tool:

"Patch EXE finished with errors: 
ERROR Failed to find the asm code that I need to patch: 
SHA1=639D15120B443F414EBD555575B96184FE201506
File=D:\SteamLibrary\steamapps\common\HaloWarsDE\xgameFinal.exe
"

Prevents game from opening.

**Comment by kornman00** [comment]
This should be fixed in v1.0.4
